### ISSUE TITLE
Pre-built image dosen't fit on a 8G sdcard

### ISSUE THREAD

**Issue by tyabus** [tmolteno/d1_build#18]
![Capture](https://user-images.githubusercontent.com/19637128/194695761-e71e1e13-f814-413f-ab3a-1f5768465d4e.PNG)

**Comment by tmolteno** [comment]
Ah, interesting. I suspect I need to make the image slightly smaller than 8GB (because the image doesn't need all 8 GB). It is the parameter called DISK_MB in the file docker-compose.yml. Currently this is set to 8000. It looks like your disk is 7960 million bytes, which is quite a bit smaller than 8GB. Are you able to try setting this parameter to something like 7500?

**Comment by tyabus** [comment]
> Ah, interesting. I suspect I need to make the image slightly smaller than 8GB (because the image doesn't need all 8 GB). It is the parameter called DISK_MB in the file docker-compose.yml. Currently this is set to 8000. It looks like your disk is 7960 million bytes, which is quite a bit smaller than 8GB. Are you able to try setting this parameter to something like 7500?

Tried to built it on Debian 11 not a long time ago with DISK_MB lowered to around 7300-7400, Got an 1.1MiB img, can you please make a pre-build with lower DISK_IMG size?

**Comment by tmolteno** [comment]
I will go for the 7.x solution and hope this works. Let's say 7.2 GB.

**Comment by tmolteno** [comment]
I'm closing this issue, as I think this is fixed in the latest release v0.4.0
